library(here)
library(compcodeR)
source(here('scripts','2019-05-17_compData_diff_disp_functions.R'))

for (i in 1:50) {
  name2 <- paste0('DEDD2.',i)
  name5 <- paste0('DEDD5.',i)
  name10 <- paste0('DEDD10.',i)
  counts2 <- simulate.DE.DD.data(dataset=name2, n.vars=20000, samples.per.cond=2)
  counts5 <- simulate.DE.DD.data(dataset=name5, n.vars=20000, samples.per.cond=5)
  counts10 <- simulate.DE.DD.data(dataset=name10, n.vars=20000, samples.per.cond=10)
  file2 <- paste0(name2,'.rds')
  file5 <- paste0(name5,'.rds')
  file10 <- paste0(name10,'.rds')
  saveRDS(counts2, file=file2)
  saveRDS(counts5, file=file5)
  saveRDS(counts10, file=file10)
  name2 <- paste0('DD2.',i)
  name5 <- paste0('DD5.',i)
  name10 <- paste0('DD10.',i)
  counts2 <- simulate.DD.only.data(dataset=name2, n.vars=20000, samples.per.cond=2)
  counts5 <- simulate.DD.only.data(dataset=name5, n.vars=20000, samples.per.cond=5)
  counts10 <- simulate.DD.only.data(dataset=name10, n.vars=20000, samples.per.cond=10)
  file2 <- paste0(name2,'.rds')
  file5 <- paste0(name5,'.rds')
  file10 <- paste0(name10,'.rds')
  saveRDS(counts2, file=file2)
  saveRDS(counts5, file=file5)
  saveRDS(counts10, file=file10)
  name2 <- paste0('DE2.',i)
  name5 <- paste0('DE5.',i)
  name10 <- paste0('DE10.',i)
  counts2 <- generateSyntheticData(dataset='name2', n.vars=20000, samples.per.cond=2, n.diffexp=1000, 
                                   fraction.upregulated=0.5, filter.threshold.mediancpm=0.5)
  counts5 <- generateSyntheticData(dataset='name5', n.vars=20000, samples.per.cond=5, n.diffexp=1000, 
                                   fraction.upregulated=0.5, filter.threshold.mediancpm=0.5)
  counts10 <- generateSyntheticData(dataset='name10', n.vars=20000, samples.per.cond=10, n.diffexp=1000, 
                                    fraction.upregulated=0.5, filter.threshold.mediancpm=0.5)
  file2 <- paste0(name2,'.rds')
  file5 <- paste0(name5,'.rds')
  file10 <- paste0(name10,'.rds')
  saveRDS(counts2, file=file2)
  saveRDS(counts5, file=file5)
  saveRDS(counts10, file=file10)
}

